#Use python as base image
FROM python:3.7.7
#use working directory
WORKDIR /app

ADD . /app

RUN pip install --trusted-host pypi.python.org -r requirements.txt
EXPOSE 5000
ENV NAME OpentoAll
CMD ["python","app.py"]
